# Day 2: Variables and Flow Control

## Learning Objectives

* use a variable to store a number
* use variables in a simple calculation
* modify variables
* write a simple `for` loop using the `range()` command
* use ‘if’, ‘else’, and ‘elif’ to check for simple conditions
* make a very basic plot


# Supplemental videos

Before beginning this module, please watch Video 2.1 *Variables and Flow* https://youtu.be/yQ_3oAa2QD0

## Beyond Python as a calculator: Jupyter Cells

The first step to make Python become more than a calculator is to write a routine (also known as a program or a code). A routine is a series of commands that can be executed in sequence. Within Jupyter, each cell forms its own little program that can be executed all at once.  For example, we may put a number into a variable and then print it:

    y = 3.0 + 6.0/7.0 - 2.0**3.0
    print(y)
    
Exercise: Execute the above code


In [ ]:
y = 3.0 + 6.0/7.0 - 2.0**3.0
print(y)

-4.142857142857142


## Warning: Variables in Jupyter are _persistent_: that is, they carry across cells. To see this, print the variable `y` in the cell below.

In [ ]:
print(y)


-4.142857142857142


You can think of a variable as a little blank space where the computer stores a thing for you.  When we write

    a = 2
    
The computer finds a blank piece of memory, writes the number `2` into it, and remembers that you called it `a`. This way, when you next write

    print(a)
    
It knows to go back and look at the place in memory called `a`.

The usage of the `=` here is somewhat different than we're used to in math.  Rather than an equation, it's an _assignment_ operator.  It reads: _take the thing on the right of the `=` (2), and put it in the memory location referred to by the thing on the left (`a`)_.

Variables may be overwritten, modified, etc.  Here's a bit of code:

    a = 10
    b = a + 3
    a = 0
    print(a,b)
    
What is the output of this program?  Why?

In [ ]:
a = 10
b = a + 3
a = 0
print(a,b)

0 13


## A simple piece of code

Consider the motion of a ball thrown vertically. It’s height y as a function of time t is given by:

$y(t) = v_0t − (1/2)gt^2$

where we’ve used the origin as the initial height. Suppose we want to compute the position of the ball at $t = 2$s, given an initial velocity of $v_0 = 10$m/s. Here is a simple code that will carry out the calculation:


    # Height of an object thrown vertically upward
    
    t = 2.0    # time at which we want the position (s)
    v0 = 10.0  # initial velocity (m/s)
    g = 9.8    # acceleration due to gravity (m/s**2)
    
    y = v0*t - 0.5*g*t**2  # compute the vertical position
    print(y)
    
    
There are few things to note about the above routine.

First, comments are used throughout the code to explain what is going on. A comment is anything that begins with a `#`, either on its own line or at the end of another. Commenting your code will help anyone who reads it later—including yourself.

Second, we assigned variables to the numbers. This is especially useful when the same quantity (like the time t) will be used multiple times throughout the routine. If you decide to change the value of that quantity, you only have to make the change in one place. Finally, blank lines have been inserted between the logical breaks in the code. The code begins with a header. The next section is where all of the variables are defined. Next is the section where the result is computed. The final section is where the output is returned. Separating the code like this improves its readability.

__Exercise: Run the code found above in the cell below__



<br>
To further improve things, we can modify the print statement to include some explanation. Change the final line of your routine to something like:

     print("The height at t = {} seconds is y = {} meters".format(t,y))
     
There are other ways to create this same output. Try the following:

     print("The height at t = ", t, "seconds is y = ", y, "meters")
     
Here, the output consists of strings and variables. Here is another method:

     print("The height at t = "+str(t)+" seconds is y = "+str(y)+" meters")
     
In this case, we have transformed the numbers into strings and then concatenated everything into a single string.  Note that in the last case we're using `+`, which concatenates the string, rather than giving multiple
arguments (separated by `,`s) to `print()`.

__Exercise: Copy the code from above in the cell below and modify it to include some explanation in the print statement.__


In [ ]:
# Height of an object thrown vertically upward

t = 1.0    # time at which we want the position (s)
v0 = 10.0  # initial velocity (m/s)
g = 9.8    # acceleration due to gravity (m/s**2)

y = v0*t - 0.5*g*t**2  # compute the vertical position
print(y)
print("The height at t = ", t, "seconds is y = ", y, "meters")
print("The height at t = {} seconds is y = {} meters".format(t,y))
print("The height at t = "+str(t)+" seconds is y = "+str(y)+" meters")

5.1
The height at t =  1.0 seconds is y =  5.1 meters
The height at t = 1.0 seconds is y = 5.1 meters
The height at t = 1.0 seconds is y = 5.1 meters


Some things to notice about this bit of code:

1. Any number that can be a non-integer has a `.0` after it.  This is to avoid confusion and a GOOD RULE TO FOLLOW
2. Python is obeying order of operations as we expect -- the last term is being evaluated as `0.5 * g * (t**2)`
3. We have copiously commented what this code does
    

## The `for` loop

If we wanted to have the position of the thrown object at a lot of times, changing the code and re-running it over and over is somewhat inefficient. Luckily for us, computers are very good at repetitive behaviour. Programming languages thus provide a few constructs that enable this – these are called ‘loops’. One of these is called a `for` loop.
The for loop is named because it embodies the idea: ‘for every X in Y, do something’. As a concrete example, if you are making something with egg yolks, you may have the following algorithm:

    for every egg I have to add:
        break the egg
        separate the yolk from the egg whites
        add the yolk to the bowl
        
In python, we can use the `for` command in this way.  Suppose we want to print all the numbers from 1 to 10.  This can be accomplished with the bit of code in the cell below:


In [ ]:

for n in range(1,11):
    print("Number",n)
print("I'm done!")


Number 1
Number 2
Number 3
Number 4
Number 5
Number 6
Number 7
Number 8
Number 9
Number 10
I'm done!


Let's dissect this bit of code a bit.  The `range` command produces a list of numbers from 1 to 10. We'll learn more about lists soon, but for now, remember that `range(a,b)` produces a list from `a` to `b-1`. (You can try this out in the cell above).

The `for` command assigns each element of this list to the variable `n`, one by one.  Notice the colon `:` after the `for` command.

The ‘do something’ part of the loop is indicated by the __indentation__ of the line:

    print("Number",n)
    
it is offset from the left by a fixed number of spaces, or a tab. It doesn’t matter which you use, as long as you are consistent – you cannot switch from using 4 spaces to 5 spaces for indentation, nor can you switch from any number of spaces to using a tab.

At the end, we remove the indentation, which signals the end of the loop.

We can, of course, do some more complicated things in the loop. For example, we may wish to print the number and its square:

    for n in range(1,11): # Produces numbers from 1 to 11-1=10 and assigns them to n one by one
        print(n,n**2)
        
Try this out! Also to try: what does `range` do with floating point values?

In [ ]:
for n in range(1,21,2):
  print(n,n**2)
print("Done.")


1 1
3 9
5 25
7 49
9 81
11 121
13 169
15 225
17 289
19 361
Done.


We can use the idea of a loop to evaluate our expression above for the position of a thrown ball for a bunch of different times.  Take your code above, and modify it so it prints the $y$ position for times $t$={0,1,2,3,4,5,6,7,8,9,10}.

(You may want to turn gravity down a smidge, say to $2$ish m/s$^2$ so the object doesn't end up below the floor with a negative position.)

In [ ]:
for t in range(0,11):

  v0 = 30.0  # initial velocity (m/s)
  g = 9.8    # acceleration due to gravity (m/s**2)
  y = v0*t - 0.5*g*t**2  # compute the vertical position
  print(y)

0.0
25.1
40.4
45.9
41.599999999999994
27.499999999999986
3.5999999999999943
-30.100000000000023
-73.60000000000002
-126.90000000000003
-190.00000000000006


We can use loops to do something other than just print numbers. We can create a new variable `s` for sum, and add all the numbers in the loop to it.

    s = 0
    for n in range(1,11):
        s = s + n
        print("I'm adding the number",n,"to the sum, which now contains the value",s)
    print("We're done! s now contains",s)
    
Try running this in the cell below.

In [ ]:
s = 0
for n in range(1,11):
    s = s + n
    print("I'm adding the number",n,"to the sum, which now contains the value",s)
print("We're done! s now contains",s)

I'm adding the number 1 to the sum, which now contains the value 1
I'm adding the number 2 to the sum, which now contains the value 3
I'm adding the number 3 to the sum, which now contains the value 6
I'm adding the number 4 to the sum, which now contains the value 10
I'm adding the number 5 to the sum, which now contains the value 15
I'm adding the number 6 to the sum, which now contains the value 21
I'm adding the number 7 to the sum, which now contains the value 28
I'm adding the number 8 to the sum, which now contains the value 36
I'm adding the number 9 to the sum, which now contains the value 45
I'm adding the number 10 to the sum, which now contains the value 55
We're done! s now contains 55


## Conditionals

Sometimes, while our program is running, we will want it to do something if some condition is fulfilled. This is accomplished in python by, not surprisingly, an `if` statement, and its relative, `else`.

For example, suppose we want to take our list of 10 numbers and print out whether they are odd or even. This is accomplished by checking to see whether the number is divisible by two. We’ll use the modulus operation that we learned about in the pre-class activities. If a number is even, its remainder when divided by 2 should be 0.

For example:

In [ ]:
N = 16
if N % 2 == 0:  # N is even
    print(N,'is even!')
else:           # N is odd
    print(N,'is odd!')

16 is even!


Make sure you understand what the above does (and try changing the number N).  Notice that, just as with the `for` command, we indent to indicate the code block to execute, and there is a colon `:` following both the condition and the `else`.

Notice the double equals sign `==` used in this piece of code. This is the comparison operator, and it is different from the assignment operator (`=`). Mixing these up is an extremely common typographical error! Here, the comparison operator checks to see whether the thing on the left hand side (the remainder of n divided by 2) and the right hand side (0) are equal.

We can use `if` statements everywhere, including in the middle of a loop:

In [ ]:
for n in range(1,11): # Produces numbers from 1 to 11-1=10 and assigns them to n one by one
    if n % 2 == 0:  # N is even
        print(n,'is even!')
    else:           # N is odd
        print(n,'is odd!')

1 is odd!
2 is even!
3 is odd!
4 is even!
5 is odd!
6 is even!
7 is odd!
8 is even!
9 is odd!
10 is even!


**Never EVER** compare variables with **floating numbers**!!!
**Never EVER** compare variables with **floating numbers**!!!
**Never EVER** compare variables with **floating numbers**!!!
**Never EVER** compare variables with **floating numbers**!!!
**Never EVER** compare variables with **floating numbers**!!!

In [ ]:
0.2 + 0.2 + 0.2 == 0.6

False

In [ ]:
0.1 + 0.2 == 0.3
print(.1+.2)


0.30000000000000004


Notice that once we're inside the `for` block of code, we indent *again* to indicate the bit of code to run in the `if` and `else` blocks.

## `and`, `or` & `not`

It may be that you have multiple conditions you need to satisfy.  Say, for example, you'd like to know whether a number is odd and divisible by 3.  You can string the conditions after an `if` together in intuitive ways.  Additionally, you can use `not` to negate a condition:

In [ ]:
for n in range(1,11):  # Produces numbers from 1 to 11-1=10 and assigns them to n one by one
    if not n % 2 == 0 and n % 3==0:   # N is odd and divisible by 3
        print(n,'is odd and divisible by three!')
    elif not n % 2 == 0:                # N is odd
        print(n,'is odd!')


1 is odd!
3 is odd and divisible by three!
5 is odd!
7 is odd!
9 is odd and divisible by three!


Make sure that you understand the above statements and why python is printing what it's printing.

## `else` and `elif`

While the above works, it would be nice if we could check a condition after a first one is false.  For example, we might rewrite the above example in the following way which eliminates the double printing of numbers:

In [ ]:
for n in range(1,11):
    if not n % 2 == 0 and n % 3==0:
        print(n,'is odd and divisible by three!')
    elif not n % 2 == 0:
        print(n,'is odd!')
    else:
        print(n,'is even!')
for n in range(1,11):
  if not n % 2 == 0:
    if not n % 2 == 0 and n % 3==0:
      print(n,'is odd and divisible by three!')
    else:
      print(n, 'is odd!')
  else:
    print(n, 'is even!')

1 is odd!
2 is even!
3 is odd and divisible by three!
4 is even!
5 is odd!
6 is even!
7 is odd!
8 is even!
9 is odd and divisible by three!
10 is even!
1 is odd!
2 is even!
3 is odd and divisible by three!
4 is even!
5 is odd!
6 is even!
7 is odd!
8 is even!
9 is odd and divisible by three!
10 is even!


Note that there is more than one way of accomplishing this.  In the cell below, write a small bit of code that produces the same output as the above but with nested if statements:

    if something1:
        if something1:
            do a thing
        else:
            do a different thing
    else:
        do a more different thing

# Putting It All Together: Make your own Function

Python user-defined funciton

```
def any_function_name(input):
    <operations>
    ...
    output = <do_something>
    return output
```



In [ ]:
import time

In [ ]:
def add1minus2(x):
    x = x + 1 - 2
    return x

In [ ]:
add1minus2(5)

4

In [ ]:
def factorial(x):
    tmp = 1
    for i in range(1,x+1):
        tmp *= i
    return tmp

def factorial_recursive(x):
    if x == 1:
        return 1
    else:
        return (x * factorial_recursive(x-1))

In [ ]:
num = 100

start = time.time()
a = factorial(num)
print('1st function takes {:.5} seconds to execute.'.format(time.time()-start))

start = time.time()
b = factorial_recursive(num)
print('2nd function takes {:.5} seconds to execute.'.format(time.time()-start))


1st function takes 8.2493e-05 seconds to execute.
2nd function takes 0.00019431 seconds to execute.


#Data Structures: Lists, Arrays, Dictionaries, and Sets


A list is a way that we store multiple items in a single variable. We can put any of type of variables into a list. Two basic examples:

In [ ]:
my_opinion = ['physics', 'is']
numbers = [9, 7, 5, 3, 1, 0, 0]

I haven't completed my_opinion. What is physics? We can use list.append() to add a new variable at the end of the list. Let's try it

In [ ]:
negative_opinion = 'boring'
my_opinion.append(negative_opinion)
print(my_opinion)

['physics', 'is', 'boring']


What if I think more highly of physics and want to change the word boring? We can delete the third object of a list with list.pop(). We have to specify which element we want to delete. Python **indexes starting at 0**. This means that the third element of fun is my_opinion[2]. We'll talk more about accessing by index of an array later, but it's important to note that you need hard brackets. Let's get rid of boring and say physics is fun!

In [ ]:
my_opinion = ['physics', 'is', 'boring']
positive_opinion = 'fun'
my_opinion.pop(2)
print(my_opinion)
my_opinion.append(positive_opinion)
print(my_opinion)

['physics', 'is']
['physics', 'is', 'fun']


What if I want to insert the word "not"? Because I don't think it's boring but it's also not exactly fun? We can use list.insert(position, object). The position is the indices we want to put the object BEFORE. Aka here, we want to put this before the third object. Note: we can use either '' or "" to define strings.

In [ ]:
my_opinion = ['physics', 'is', 'fun']
my_opinion.insert(2,"not")
print(my_opinion)

We can figure out some more properties of lists like its length or how many times something occurs in a list. If we have a list of numbers, we can also find out the maximum and minimum. Let's look at how many, say, apples get eaten in a week.

In [ ]:
apples_eaten = [2, 2, 2, 1, 0, 2, 3]
print("The number of days in a week is", len(apples_eaten))
print("The maximum and minimum numbers of apples eaten in a day are (respectively):")
print(max(apples_eaten))
print(min(apples_eaten))

print("We ate two apples", apples_eaten.count(2), "days this week")

print("The index of the day we first ate one apple is",apples_eaten.index(1))
print("But we first ate one apple on day", apples_eaten.index(1)+1 )

print("This week we ate a total of",sum(apples_eaten), "apples")


To install Numpy on Ubuntu systems, run

    sudo apt-get install python-numpy

The main object is ndarray (N-dimensional array).

The data type is specified by another NumPy object called dtype (data-type); each ndarray is associated with only one type of dtype.

The number of the dimensions and items in an array is deinfed by its shape, which is a tuple of N-positive intergers that specifies the size for each dimension. The dimensions are defined as axes and the number of axes are defined as rank.

Once you define the size of Numpy arrays at the time of createion, it remains unchanged whereas the Python lists can grow or shrink in size

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3]) #define a new ndarray by using array() function
print(a)
print(type(a)) #check the type of the object
a.dtype #check the data-type of the ndarray object

[1 2 3]
<class 'numpy.ndarray'>


dtype('int64')

the ndarray object, a, we just created, has one axis, and then its rank is 1, while its shape should be (3,1).

ndim is to get the axes;

size is to know the array length

shape is to get its shape

In [ ]:
a.ndim

1

In [ ]:
a.size

3

In [ ]:
a.shape

(3,)

To create another array which has rank 2 (2 axes), each of axes has length 2

In [ ]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b.ndim

2

In [ ]:
b.size

4

In [ ]:
b.shape

(2, 2)

**itemsize** atttribute is important because it defines the size in bytes of each item in the array

In [ ]:
b.itemsize

8

**data** attribute is the buffer containing the actual elements of the array

In [ ]:
b.data

##Create an Array

use array() function

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(c)

numpy.ndarray

array() also accepts tuples

In [ ]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(d)

numpy.ndarray

array() also accepts mixed lists and tuples

In [ ]:
e = np.array([(1,2,3),[4,5,6],(7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(e)

numpy.ndarray

## Types of Data

NumPy arrays can contain a wide variety of data types

In [ ]:
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [ ]:
g.dtype

dtype('<U1')

In [ ]:
g.dtype.name #To get the data type name

'str32'

##The dtype Option

You can define the dtype using the dtype option as argument of the function

In [ ]:
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

##Intrinsic Creation of an Array

###zeros() function

In [ ]:
np.zeros((3,3)) #Note: (3,3) <--need the extra () enclosed to specify a 3-by-3 zero matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(3,3) #Error..

TypeError: ignored

###ones() function

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###arange() function

arange(start, stop(exclusive), step)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,12,3) # start, end(exclusive), step

array([0, 3, 6, 9])

In [ ]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

###reshape() function

divides a linear array in different parts in the manner specified by the shape argument

In [ ]:
np.arange(0,12).reshape(3,4) # 3 rows, 4 columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###linspace() function

linspace(start, stop(exclusive), number of elements)

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

###random() function

in the numpy.random module

In [ ]:
np.random.random(3)

array([0.80003846, 0.19226401, 0.53230656])

To create multidimensional array, pass the size of the array as an argument

In [ ]:
np.random.random((3,4)) # 3 rows, 4 columns

array([[0.82397258, 0.21168989, 0.45378402, 0.26916356],
       [0.76909937, 0.40572542, 0.43176281, 0.66880022],
       [0.17760768, 0.25044993, 0.18799054, 0.68445106]])

##Arithmetic Operators

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a+4

array([4, 5, 6, 7])

In [ ]:
a*2

array([0, 2, 4, 6])

Note the element-wise operations between two arrays:

In [ ]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [ ]:
a + b

array([ 4,  6,  8, 10])

In [ ]:
a - b

array([-4, -4, -4, -4])

In [ ]:
a * b

array([ 0,  5, 12, 21])

In [ ]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [ ]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

For multidimensional case

In [ ]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

##Increment and Decrement Operators

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a += 1
a

array([1, 2, 3, 4])

In [ ]:
a -= 1
a

array([0, 1, 2, 3])

In [ ]:
a *= 2
a

array([0, 2, 4, 6])

##Aggregate Functions

In [ ]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [ ]:
a.sum()

15.0

In [ ]:
a.min()

0.3

In [ ]:
a.max()

5.7

In [ ]:
a.mean()

3.0

In [ ]:
a.std()

2.0079840636817816

##Indexing, Slicing, and Iterating

###Indexing

In [ ]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[4]

14

In [ ]:
a[-1]

15

In [ ]:
a[-6]

10

To select multiple items at once, pass the array of indices in square brackets

In [ ]:
a[[1,3,4]]

array([11, 13, 14])

Two-dimensional case,

defined by two axes, where axis 0 is the row and axis 1 is the column.

Indexing should be a pair of values: first value is the index of the row and the second is the index of the column.

pass in the square brackets: [row index, coulmn index]

In [ ]:
A = np.arange(10,19).reshape(3,3)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[1,2] #index starts with 0

15

###Slicing

In [ ]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[1:5] #not include the last element

array([11, 12, 13, 14])

To skip a specific number of following items:

[start:stop:step]

In [ ]:
a[1:5:2]

array([11, 13])

More examples

In [ ]:
a[::2] #starts at index 0, stops at max index, skip 1 element

array([10, 12, 14])

In [ ]:
a[:5:2] #starts at index 0, stops at index 5, skip 1 element

array([10, 12, 14])

In [ ]:
a[:5:] #starts at index 0, stops at index 5, skip 0 element

array([10, 11, 12, 13, 14])

For two-dimensional array...

If you want to extract only the first row,

In [ ]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[0,:] #slice at row 0 (first row)

array([10, 11, 12])

extract the first column,

In [ ]:
A[:,0]

array([10, 13, 16])

If you want to extract a smaller matrix,

In [ ]:
A[0:2, 0:2] #Note: from row 0 to row 1, from column 0 to column 1..

array([[10, 11],
       [13, 14]])

If you want to specify an array of indices,

In [ ]:
A[[0,2], 0:2] # row 0 and row 2, from column 0 to column 1

array([[10, 11],
       [16, 17]])

###Iterating an Array

In [ ]:
for i in a:
  print(i)

10
11
12
13
14
15


For two-dimensional array, didn't need nested for loop. Actually, if you apply the for loop to a matrix, it will always perform a scan according to the first axis

In [ ]:
for row in A:
  print(row)

[10 11 12]
[13 14 15]
[16 17 18]


To make a iteration element by element, use the flat attribute on the matrix object...

In [ ]:
A.flat #didn't show anything

In [ ]:
for item in A.flat:
  print(item)

10
11
12
13
14
15
16
17
18


The **apply_along_axis()** function is used to launch an aggregate function that returns a value calculated for every single column or on every single row.

This function takes three arguments: the aggregate function, the axis on which to apply the iteration, and the array.

If axis=0, the iteration evaluates the elements column by column. (along axis 0 direction)

If axis=1, the iteration evaluates the elements row by row. (along axis 1 direction)

In [ ]:
A

In [ ]:
np.apply_along_axis(np.mean, axis=0, arr=A)

In [ ]:
np.apply_along_axis(np.mean, axis=1, arr=A)

You can also use this function for user-defined function...

In [ ]:
def foo(x):
  return x/2

In [ ]:
np.apply_along_axis(foo, axis=0, arr=A)

In [ ]:
np.apply_along_axis(foo, axis=1, arr=A)

##Conditions and Boolean Arrays

Use the conditions and Boolean opearators to extract elements

In [ ]:
A = np.random.random((4,4))
A

In [ ]:
A < 0.5

In [ ]:
A[A < 0.5]

##Shape Manipulation
###reshape() fucntion

returns a new array and can be used to create new objects

In [ ]:
a = np.random.random(12)
a

In [ ]:
A = a.reshape(3,4)
A

###shape attribute

If you want to modify the object without create a new object, use shape attribute to pass the tuple containing the new dimensions directly

In [ ]:
a.shape = (3, 4) #Note: use TUPLE
a

###ravel() function

Inverse operation: convert a two-dimensional array into a one-dimensional array

In [ ]:
a = a.ravel()
a

In [ ]:
a.shape = (12)
a

###transpose() function

In [ ]:
A

In [ ]:
A.transpose()

##Array Manipulation
###Joining Arrays

merge multiple arrays to form a new one that contains all of the arrays

**vstack() function**

combines the second array as new rows of the first array. The array grows in a vertical direction.

In [ ]:
A = np.ones((3,3))
B = np.zeros((3,3))
np.vstack((A,B)) #argument must be in tuple

**hstack() function**

combines the second array as new columns of the first array. in horizontal direction

In [ ]:
np.hstack((A,B))

**column_stack()** and **row_stack()** are used with one-dimensional arrays

In [ ]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
np.column_stack((a,b,c)) #arg must be tuple

In [ ]:
np.row_stack((a,b,c))

###Splitting Arrays

In [ ]:
A = np.arange(16).reshape((4,4))
A

**hsplit() function**

split the array horizontally, meaning the width of the array is divided into **2** parts

In [ ]:
[B, C] = np.hsplit(A, 2) # second arg means to divide into 2 parts
B

In [ ]:
C

**vsplit() function**

split the array vertically, meaning the height of the array is divided into **2** parts

In [ ]:
[B, C] = np.vsplit(A, 2)
B

In [ ]:
C

**split() function**

allows you to split the array into nonsymmetrical parts

You also need to specify the indices of the parts to be divided

If axis = 0, the indices will be rows; if axis = 1, the indices will be columns.

For example, if you want to divide matrix A into three parts, the first of which is the first column, the second contains the second and the third column, and the third is the last column, you must specify in the following way:

In [ ]:
[A1, A2, A3] = np.split(A, [1,3], axis = 1) # [1,3] means starting at index 1 and ending at index 2
A1

In [ ]:
A2

In [ ]:
A3

Do the same thing by row:

In [ ]:
[A1, A2, A3] = np.split(A, [1,3], axis=0)
A1

In [ ]:
A2

In [ ]:
A3

##Copies or Views of Objects

The following assignments are just the views of the original array, not a copy!!

In [ ]:
a = np.array([1,2,3,4])
b = a
b

In [ ]:
a[2] = 0
b #change in a[2] changes b[2] as well

In [ ]:
c = a[0:2]
c #slicing

In [ ]:
a[0] = 0
c #change in a[0] changes c[0] as well

**copy() function** generates a complete and distinct array

In [ ]:
a = np.array([1,2,3,4])
c = a.copy() #real copy
c

In [ ]:
a[0] = 0
c #change in a[0] doesn't affect c[0]

##Loading and Saving Data in Binary Files

###save()

The file wil automatically be given the .npy extension


In [ ]:
data = np.random.random(12).reshape((4,3))
data

In [ ]:
np.save('saved_data', data)

###load()

In [ ]:
loaded_data = np.load('saved_data.npy')
loaded_data

## List comprehesion
Task: create a list that contains a series of consecutive sqaured odd numbers from 1 to 19, i.e.,


```
input = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
output = [1, 9, 25, 49, 81, 121, 169, 225, 289, 361]
```



In [ ]:
n_start, n_end, n_step = 1, 20, 2

In [ ]:
# 1st method
# simple for loop
start = time.time()
list1 = []
for i in range(n_start, n_end, n_step):
    tmp = i**2
    list1.append(tmp)
print('Execution time: {:.5} seconds.'.format(time.time()-start))
#list1, type(list1)

Execution time: 0.00014806 seconds.


In [ ]:
# 2nd method
# numpy linspace
start = time.time()
list1 = (np.arange(n_start, n_end, n_step) **2).tolist()
print('Execution time: {:.5} seconds.'.format(time.time()-start))
#list2, type(list2)

Execution time: 0.00017476 seconds.


In [ ]:
# 3rd method
# list comprehesion
start = time.time()
list3 = [i**2 for i in range(n_start, n_end, n_step)]
print('Execution time: {:.5} seconds.'.format(time.time()-start))
#list3, type(list3)

Execution time: 0.00012803 seconds.


In [ ]:
# 1st method
# simple for loop
start = time.time()
list1 = []
for i in range(n_start, n_end, n_step):
    list1.append(i**2)
print('Execution time: {:.5} seconds.'.format(time.time()-start))
#list1, type(list1)

Execution time: 0.00016093 seconds.
